security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

scope: server

spring:
  data:
    mongodb:
      host: account-mongodb
      database: db
      port: 27017

server:
  servlet:
    context-path: /accounts
  port: 6000

feign:
  hystrix:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 160000000
        readTimeout: 160000000
