version: '2.1'
services:
  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  notification-service:
    build: notification-service
    ports:
      - 8000:8000


